#ifndef NF_GLOBAL_H
#define NF_GLOBAL_H

#define NF_VERSION_1 "1.1"
#define NF_VERSION_2 "1.2"
#define NF_VERSION_3 "1.3"
#define NF_VERSION_OTHER "1.*"
#define RESERVE_INT 0
#define RESERVE_DOUBLE 0.000
#define RESERVE_STRING "\"0\""
#define TAB "// "
#define ENDL "\n"
#define QUOTATION "\""

#define VERSION "VERSION"
#define SHEET_COUNT "SHEET COUNT"
#define SHEET_INFO "SHEET INFO"
#define PIECE_CENTER_COUNT "PIECE CENTER COUNT"
#define PIECE_CENTER_INFO "PIECE CENTER INFO"
#define PIECE_OFFSET_COUNT "PIECE OFFSET COUNT"
#define PIECE_OFFSET_INFO "PIECE OFFSET INFO"

#define LINE_HEADER 1
#define LINE_VERSION 2
#define LINE_SHEET_COUNT 2
#define LINE_SHEET_INFO 10
#define LINE_PIECE_CENTER_COUNT 2
#define LINE_PIECE_CENTER_INFO 7
#define LINE_PIECE_OFFSET 8

#define NF_TNF_MAXLINE 1024

#endif // NF_GLOBAL_H
